name: Copy File to Another Repository

on:
  push:
    paths:
      - 'local_getting_used_pandas.ipynb'

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Copy file to destination repository, Commit and push changes
      run: |
        cp local_getting_used_pandas.ipynb Getting-used-to-Pandas/
        ls -la Getting-used-to-Pandas/
        git -C Getting-used-to-Pandas/ add .
        git -C Getting-used-to-Pandas/ commit -m "Copy local_getting_used_pandas.ipynb to destination repository"
        git -C Getting-used-to-Pandas/ push origin main
      if: success()

    - name: Check if file exists in source repository
      run: |
        if [ -f "local_getting_used_pandas.ipynb" ]; then
          echo "File exists in source repository. This is an error."
          exit 1
        fi
