name: Copy and Rename File to Another Repository

on:
  push:
    paths:
      - 'local_getting_used_pandas.ipynb'

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Copy and rename file to destination repository
      run: |
        today=$(date +"%Y-%m-%d")
        destination_directory=$GITHUB_WORKSPACE/Getting-used-to-Pandas
        mkdir -p $destination_directory
        cp local_getting_used_pandas.ipynb $destination_directory/${today}.ipynb
      if: success()

    - name: Change directory to destination repository
      run: cd $GITHUB_WORKSPACE/Getting-used-to-Pandas/

    - name: Configure Git
      run: |
        git config user.email "koak1107@gmail.com"
        git config user.name "kyeob1107"

    - name: Commit and push changes to destination repository
      run: |
        git add .
        git commit -m "Copy and rename local_getting_used_pandas.ipynb to 오늘날짜이름파일로"
        git push origin main  # 또는 원하는 브랜치
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
