name: Copy File to Another Repository

on:
  push:
    paths:
      - 'local_getting_used_pandas.ipynb'

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Copy file to destination repository
      run: |
        cp local_getting_used_pandas.ipynb ../Getting-used-to-Pandas/
        ls -la ../Getting-used-to-Pandas/
      if: success()

    - name: Change directory to destination repository
      run: cd ../Getting-used-to-Pandas/

    - name: Configure Git
      run: |
        git config user.email "koak1107@gmail.com"
        git config user.name "kyeob1107"

    - name: Check if file exists in source repository
      run: |
        if [ -f "../Commitment-for-Getting-used-to-Pandas/local_getting_used_pandas.ipynb" ]; then
          echo "File exists in source repository. This is an error."
          exit 1
        fi

    - name: Commit and push changes to destination repository
      run: |
        git add .
        git commit -m "Copy local_getting_used_pandas.ipynb to destination repository"
        git push origin main  # 또는 원하는 브랜치
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

