name: Copy File from Commitment-for-Getting-used-to-Pandas to Getting-used-to-Pandas

on:
  push:
    paths:
      - 'local_getting_used_pandas.ipynb'

jobs:
  copy_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commitment-for-Getting-used-to-Pandas Repository
        uses: actions/checkout@v2
        with:
          repository: kyeob1107/Getting-used-to-Pandas
          path: Commitment-for-Getting-used-to-Pandas/  # 여기에 '/'를 붙여서 하위 디렉토리에 저장하도록 함

      - name: Debugging - List files in Commitment-for-Getting-used-to-Pandas
        run: |
          cd Commitment-for-Getting-used-to-Pandas
          ls -l

      - name: Copy File to Getting-used-to-Pandas Repository
        run: |
          today=$(date +"%Y-%m-%d")
          destination_file="Getting-used-to-Pandas/${today}.ipynb"
          cp "local_getting_used_pandas.ipynb" "$destination_file"

      - name: Commit and Push to Getting-used-to-Pandas Repository
        run: |
          git config --global user.email "koak1107@gmail.com"
          git config --global user.name "kyeob1107"
          git add "Getting-used-to-Pandas/${today}.ipynb"
          git commit -m "${today} 타이핑한 내용"
          git push origin main
        working-directory: Commitment-for-Getting-used-to-Pandas

